# Generated by Django 4.2.5 on 2023-09-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="estado",
            field=models.CharField(
                choices=[("activo", "Activo"), ("bloqueado", "Bloqueado")],
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numero_cuenta",
            field=models.IntegerField(unique=True),
        ),
    ]
