# Generated by Django 4.2.5 on 2023-09-08 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_useraccount_estado_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={"verbose_name": "Usuaro", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterField(
            model_name="abonos",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="cargos",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
