# Generated by Django 4.2.5 on 2023-09-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_useraccount_options_alter_abonos_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonos",
            options={"verbose_name": "Abonos", "verbose_name_plural": "Abonos"},
        ),
        migrations.AlterModelOptions(
            name="cargos",
            options={"verbose_name": "Cargos", "verbose_name_plural": "Cargos"},
        ),
        migrations.AddField(
            model_name="abonos",
            name="retencion",
            field=models.BooleanField(default=False),
        ),
    ]
