# Generated by Django 4.2.5 on 2023-09-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_abonos_options_alter_cargos_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AddField(
            model_name="useraccount",
            name="intentos_fallidos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numero_cuenta",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
