# Generated by Django 4.2.5 on 2023-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_useraccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="numero_cuenta",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
