# Generated by Django 4.2.5 on 2023-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_useraccount_numero_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="saldo_inicial",
            field=models.IntegerField(default=0),
        ),
    ]
